id: P000668
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20027
  title: བོད་ཀྱི་གསོ་རིག་ཆོས་འབྱུང་བཻཌཱུརྱའི་འཕྲེང་བ
  author: ''
  volumes:
    41037b09d8754fe09a7f914cafad52ca:
      image_group_id: I1KG1056
      title: ''
      volume_number: 1
      total_pages: 170
